spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/my_db?useSSL=false&amp;serverTimezone=UTC
    username: postgres
    password: test
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: validate
