spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/my_db?useSSL=false&amp;serverTimezone=UTC
    username: postgres
    password: postgres
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate
